/*
- Generated by ChatGPT

Create a simple C# program that does the following:

Ask the user for a number and check if it is positive, negative, or zero, and print a complete message.
*/


Console.Write("Enter a number: ");

float number = float.Parse(Console.ReadLine());

if (number > 0)
{
    Console.WriteLine("Positive");
}
else if (number < 0)
{
    Console.WriteLine("Negative");
}
else
{
    Console.WriteLine("Zero");
}