'''
Inspired by the video "If numbers were alphabetized" from the YouTube channel "VSauce", where numbers are alphabetized based on their names in English.

Source: https://www.youtube.com/shorts/C78GiUCKF9g
'''

# List generated by my friend ChatGPT.
number_names = 'zero, one, two, three, four, five, six, seven, eight, nine, ten, eleven, twelve, thirteen, fourteen, fifteen, sixteen, seventeen, eighteen, nineteen, twenty, thirty, forty, fifty, sixty, seventy, eighty, ninety, one hundred'


def main():
    # Create a dictionary from the list of number names.
    numbers_dict = create_numbers_dict(number_names)

    # Sort the dictionary in alphabetical order based on the names.
    numbers_in_alphabetical_order = sort_numbers_in_alphabetical_order(
        numbers_dict)

    # Sort the dictionary in reverse alphabetical order based on the names.
    numbers_in_reverse_alphabetical_order = sort_numbers_in_reverse_alphabetical_order(
        numbers_dict)

    # Display the sorted number names in alphabetical order.
    display_number_names_in_order(numbers_in_alphabetical_order, 'ascending')

    # Display the sorted number names in reverse alphabetical order.
    display_number_names_in_order(
        numbers_in_reverse_alphabetical_order, 'descending')


def create_numbers_dict(number_names):
    '''
    Creates a dictionary where keys are indices and values are the corresponding number names.
    '''
    number_names_list = [name.strip() for name in number_names.split(',')]
    return {i: number_names_list[i] for i in range(len(number_names_list))}


def sort_numbers_in_alphabetical_order(numbers_dict):
    '''
    Sorts the dictionary items based on the value (number names) in alphabetical order.
    '''
    return dict(sorted(numbers_dict.items(), key=lambda item: item[1]))


def sort_numbers_in_reverse_alphabetical_order(numbers_dict):
    '''
    Sorts the dictionary items based on the value (number names) in reverse alphabetical order.
    '''
    return dict(sorted(numbers_dict.items(), key=lambda item: item[1], reverse=True))


def display_number_names_in_order(sorted_numbers_dict, ordering):
    '''
    Displays the first and last 10 names from the sorted dictionary based on the ordering type.
    '''
    if ordering == 'ascending':
        print('=' * 40)
        print('First 10 numbers in alphabetical order:')
        print()
        display_first_10_names(sorted_numbers_dict)
        print()
        print('-' * 40)
        print()
        print('Last 10 numbers in alphabetical order:')
        print()
        display_last_10_names(sorted_numbers_dict)
        print('=' * 40)
        print()

    elif ordering == 'descending':
        print('=' * 40)
        print('First 10 numbers in reverse alphabetical order:')
        print()
        display_first_10_names(sorted_numbers_dict)
        print()
        print('-' * 40)
        print()
        print('Last 10 numbers in reverse alphabetical order:')
        print()
        display_last_10_names(sorted_numbers_dict)
        print('=' * 40)
        print()

    else:
        print('Error: Unknown ordering type. Please use "ascending" or "descending".')


def display_first_10_names(sorted_numbers_dict):
    '''
    Display the first 10 names from the sorted dictionary.
    '''
    numbers = list(sorted_numbers_dict.keys())
    names = list(sorted_numbers_dict.values())

    # Display the first 10 names from the sorted dictionary.
    # Ensure we do not go out of bounds if there are fewer than 10 items.
    for i in range(0, min(10, len(numbers))):
        number = numbers[i]
        name = names[i]
        print(f'{number}: {name}')


def display_last_10_names(sorted_numbers_dict):
    '''
    Display the last 10 names from the sorted dictionary.
    '''
    numbers = list(sorted_numbers_dict.keys())
    names = list(sorted_numbers_dict.values())

    # Display the last 10 names from the sorted dictionary.
    # Ensure we do not go out of bounds if there are fewer than 10 items.
    for i in range(max(0, len(numbers) - 10), len(numbers)):
        number = numbers[i]
        name = names[i]
        print(f'{number}: {name}')


if __name__ == '__main__':
    main()
