'''
Generate a random number between 1 and 10. Ask the user to guess the number and print a message based on whether they get it right or not.
'''


import random


def main():
	random_num = generate_random_num()
	user_guess = get_user_guess()
	is_user_guess_right = check_user_guess(random_num, user_guess)
	display_result(random_num, user_guess, is_user_guess_right)


def generate_random_num() -> int:
	return random.randint(1, 10)


def get_user_guess() -> int:
	print('The computer generated a number between 1 and 10.')
	while True:
		try:
			guess = int(input('Enter your guess: '))
			if 1 <= guess <= 10:
				return guess
			else:
				raise ValueError
		except ValueError:
			print('Please enter an integer number between 1 and 10.\n')


def check_user_guess(random_num: int, user_guess: int) -> bool:
	return random_num == user_guess


def display_result(random_num: int, user_guess: int, is_user_guess_right: bool) -> None:
	print(f'\nYour guess: {user_guess}')
	print(f'Number generated by the computer: {random_num}')

	if is_user_guess_right:
		print('You\'re right!')
	else:
		print('You\'re wrong!')


if __name__ == '__main__':
	main()
